config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products
  resources :carts, only: [:index]
  post '/add_to_cart/:product_id', to: 'carts#create', as: 'add_to_cart'
  post '/update_quantity', to: 'carts#update_quantity', as: 'update_quantity'
  delete '/delete_cart_variants/:cart_variant_id', to: 'carts#delete_cart_variant', as: 'delete_cart_variant'

  resources :orders, only: [:show]
  post '/create_order/:cart_id', to: 'orders#show', as: 'create_order'

  resources :payments, only: [:create]

  root to: 'products#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	has_many :cart_variants
	has_many :variants, through: :cart_variants

  def total_price
    total_amount = 0
    self.cart_variants.each do |cart_variant|
    total_amount += ( (cart_variant.variant.product.price)*(cart_variant.quantity) )
    end
    total_amount
  end

end

app/models/cart_variant.rb
class CartVariant < ApplicationRecord
  belongs_to :cart
  belongs_to :variant
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true, optional: true
  mount_uploader :photo, ImagesUploader

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_one :payments
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :variant
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :variants
  has_many  :images, as: :imageable
  accepts_nested_attributes_for :images

end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :cart
	has_many :orders
  has_many :payments

  after_create :create_cart


  def create_cart
    c = self.build_cart
    c.save
  end



end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
  has_many :cart_variants
  has_many :carts, through: :cart_variants
  has_many :order_items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	protect_from_forgery with: :exception

  def alert(type, message)
    flash[type] = message
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
  end

  def create
    @product = Product.find(params[:product_id])
    variant = @product.variants.first

    cart_variant = current_user.cart.cart_variants.where(variant_id: variant.id).first
    if cart_variant
      if cart_variant.quantity >= 5
        alert(:warning,'Product can be Addded at max 5 times')
        redirect_to products_path
      else
        cart_variant.update(quantity: cart_variant.quantity + 1)
        alert(:success,'Added to the cart Successfully')
        redirect_to products_path
      end
    elsif current_user.cart.cart_variants.create(variant_id: variant.id, quantity: 1)
      alert(:success,'Added to the cart Successfully')
      redirect_to products_path
    else
      alert(:warning,'Not added to the cart Successfully')
      redirect_to products_path
    end

  end

  def update_quantity

    cart_variant = current_user.cart.cart_variants.find(params[:cart_variant_id])
    cart_variant.update(quantity: params[:cart_variant_quantity])

    render json: {
      message: 'success',
      total_amount: (cart_variant.variant.product.price*cart_variant.quantity).to_f.to_s,
      id: cart_variant.id,
      total_price: current_user.cart.total_price.to_f.to_s
    }

  end

  def delete_cart_variant
    @cart_variant = current_user.cart.cart_variants.find(params[:cart_variant_id])
    @cart_variant.destroy
    alert(:success,'Product Deleted Successfully')
    redirect_to carts_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @orders = current_user.orders
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def create
    begin
      customer_id = Stripe::Customer.create(email:  params[:stripeEmail], source: params[:stripeToken]).id
      charge = Stripe::Charge.create(
        customer:     customer_id,
        amount:       (current_user.cart.total_price*100).to_i,
        description:  "Order user##{current_user.id} Payment",
        currency:     'USD'
      )

      cur_order = current_user.orders.create(cost: current_user.cart.total_price, order_date: Time.new)
      current_user.payments.create(transaction_id: charge.id, amount: current_user.cart.total_price, order_id: cur_order.id )

      current_user.cart.cart_variants.each do |cart_variant|
        product = cart_variant.variant.product
        cur_order.order_items.create!(name: product.name, quantity: cart_variant.quantity,
         price: product.price, variant_id: cart_variant.variant.id )
      end

      current_user.cart.cart_variants.destroy_all

      alert(:success, 'Order Created Successfully')
      redirect_to cur_order

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to :back
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def show
	end

	def edit
	end

	def update
		if @product.update_attributes(product_params)
			alert(:success, 'Product Updated Successfully')
			redirect_to products_path
		else
			render 'edit'
		end
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)

		if @product.save
		  alert(:success,'Product Created Successfully')
			redirect_to products_path
		else
			render 'new'
		end
	end

	def destroy
		@product.destroy
		alert(:success,'Product Deleted Successfully')
		redirect_to products_path
	end

	private

	def set_product
		@product = Product.find(params[:id])
	end

	def product_params
		params.require(:product).permit(:name, :quantity, :price, images_attributes: [:photo, :id, :_destroy])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-#{bootstrap_class_for(msg_type)} fade in", role: 'alert') do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <div id="show-notice" class="alert alert-success hidden top10" role="alert"></div>
  <nav class="navbar navbar-light bg-faded">
    <div class="collapse navbar-toggleable-xs" id="navbar-header">
      <a class="navbar-brand" href="#">Cart</a>
    </div>
  </nav> <!-- /navbar -->
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <hr/>
      <div class="row" style="text-align:center">
        <div class="col-md-3">
          <strong> <label class='control-label'> Name </label> </strong>
        </div>
        <div class="col-md-2">
          <strong> <label class='control-label'> Qunatity </label> </strong>
        </div>
        <div class="col-md-2">
          <strong> <label class='control-label'> Unit Price </label> </strong>
        </div>
        <div class="col-md-3">
          <strong> <label class='control-label'> Picture </label> </strong>
        </div>
        <div class="col-md-2">
          <strong> <label class='control-label'> Total Price </label> </strong>
        </div>
      </div>
      <hr/>
      <% current_user.cart.cart_variants.each do |cart_variant| %>
        <div class="row" style="text-align:center">
          <div class="col-md-3" >
            <%= cart_variant.variant.product.name%>
            <br/>
            <strong> <%=  link_to "Remove" ,delete_cart_variant_path(cart_variant.id),data: { confirm: 'Are you sure?'}, method: :delete %>  </strong>
          </div>
          <div class="col-md-2">
            <%= select_tag :quantity, options_for_select([["1",1],["2",2],["3",3],["4",4],["5",5]],cart_variant.quantity), class: 'form-control change-quantity', data: {cart_variant_id: cart_variant.id} %>
        </div>
          <div class="col-md-2">
            <%= cart_variant.variant.product.price %>
          </div>
          <div class="col-md-3">
            <%= image_tag cart_variant.variant.product.images.first.photo_url(:thumb) , class:"img-circle" %>
          </div>
          <div class="col-md-2" id="total-amount-<%= cart_variant.id %>">
            <%= (cart_variant.variant.product.price)*(cart_variant.quantity) %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
  <div class="row" style="text-align:center">
  <hr/>
    <div class="col-md-2 col-md-offset-6" >
      <strong> Total amount: </strong>
    </div>
    <div class="col-md-2">
      <strong id="total-price"> <%= current_user.cart.total_price %> </strong>
    </div>
    <div class="col-md-2" >
      <%= form_for( current_user.cart, url: payments_path, method: :post) do |f|%>
        <script
          src="https://checkout.stripe.com/checkout.js"
          class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-zipCode='true'
          data-email="<%= current_user.email %>"
          data-description="Order Payment"
          data-name="e_commerce"
          data-locale="auto">
        </script>
      <% end %>
  </script>
    </div>
    <hr/>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", "application" %>
  </head>

  <body>
    <div class="container top10">
      <%= flash_messages %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">
  <div id="show-notice" class="alert alert-success hidden top10" role="alert"></div>
  <nav class="navbar navbar-light bg-faded">
    <div class="collapse navbar-toggleable-xs" id="navbar-header">
      <a class="navbar-brand" href="#">Orders</a>
    </div>
  </nav> <!-- /navbar -->
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <hr/>
      <div class="row">
        <div class="col-md-4">
         <strong> <label class='control-label'> Order_ID </label> </strong>
        </div>
        <div class="col-md-4">
          <strong> <label class='control-label'> Total Amount </label> </strong>
        </div>
        <div class="col-md-4">
          <strong> <label class='control-label'> Date </label> </strong>
        </div>
      </div>
      <hr/>
      <% @orders.each do |order| %>
        <div class="row">
          <div class="col-md-4">
            <%= order.id %>
          </div>
          <div class="col-md-4">
            <%= order.cost %>
          </div>
          <div class="col-md-4">
            <%= order.order_date %>
          </div>
        </div>
        <hr/>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= nested_form_for @product, multipart: true do |f|%>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <form>
        <fieldset class="form-group">
          <strong> <%= f.label :name, class: 'control-label' %> </strong>
          <%= f.text_field :name, class: 'form-control' %>
        </fieldset>
        <fieldset class="form-group">
          <strong> <%= f.label :price, class: 'control-label' %> </strong>
          <%= f.text_field :price, class: 'form-control' %>
        </fieldset>
        <fieldset class="form-group">
          <strong> <label class='control-label'> Choose a Photo</label> </strong>
          <%= f.fields_for :images do |p| %>
            <div class="row">
              <div class="col-md-8">
                <%= p.file_field :photo, class: 'form-control' %>
              </div>
              <div class="col-md-4">
                <%= p.link_to_remove "Remove this photo"%>
              </div>
            </div>
          <% end %>
          <div>
          <%= f.link_to_add "Add a photo", :images %>
          </div>
        </fieldset>
        <fieldset class="form-group" style="text-align: right">
          <%= f.submit %>
        </fieldset>
      </form>
    </div>
  </div>

<% end -%>

app/views/products/edit.html.erb
<div class="container">
  <nav class="navbar navbar-light bg-faded">
    <div class="collapse navbar-toggleable-xs" id="navbar-header">
      <a class="navbar-brand" href="#">Edit</a>
    </div>
  </nav> <!-- /navbar -->

  <%= render "form" %>

</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-6">
      <strong><%= link_to('View Cart', carts_path) %></strong>
    </div>
    <div class="col-md-2">
      <strong><%= link_to('Change password', edit_user_registration_path) %></strong>
    </div>
    <div class="col-md-2">
      <strong><%= link_to('Logout', destroy_user_session_path) %></strong>
    </div>

  </div>
</div>

<!-- <div style="text-align: center"><h1>E-Commerce</h1> </div> -->
<div class="container">
	<nav class="navbar navbar-light bg-faded">
    <div class="collapse navbar-toggleable-xs" id="navbar-header">
      <a class="navbar-brand" href="#">Index</a>
    </div>
  </nav> <!-- /navbar -->
  <% @products.in_groups_of(3, false).each do |grouped_product| %>
		<div class="row">
			<%grouped_product.each do |product|%>
				<div class="col-xs-4" style="text-align:center">
					<%= image_tag product.images.first.photo_url(:thumb) , class:"img-circle" %>
					<h4>
						<%= product.id %>.
						<%= link_to product.name, product %>
					</h4>
					<div class="row">
						<div class="col-md-4">
							<%=  link_to "Edit", edit_product_path(product) %>
						</div>
            <div class="col-md-4">
              <%= form_for( product, url: add_to_cart_path(product.id), method: :post) do |f|%>
                <%= f.submit "Add to Cart" %>
              <% end %>
            </div>
						<div class="col-md-4">
            </div>
							<%=  link_to "Delete", product,data: { confirm: 'Are you sure?'}, method: :delete %>
					</div>
					<hr />
				</div>
			<% end %>
		</div>
	<% end -%>
  <%= link_to "Add new Product", new_product_path %>

</div>

app/views/products/new.html.erb
<div class="container">
  <nav class="navbar navbar-light bg-faded">
    <div class="collapse navbar-toggleable-xs" id="navbar-header">
      <a class="navbar-brand" href="#">Edit</a>
    </div>
  </nav> <!-- /navbar -->

  <%= render "form" %>

</div>

app/views/products/show.html.erb
<div class="container">
  <nav class="navbar navbar-light bg-faded">
    <div class="collapse navbar-toggleable-xs" id="navbar-header">
      <a class="navbar-brand" href="#">Show</a>
    </div>
  </nav>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <hr/>
    <div class="row" style="text-align:center">
      <div class="col-md-4">
        <strong> <label class='control-label'> Name </label> </strong>
      </div>
      <div class="col-md-4">
        <strong> <label class='control-label'> Price </label> </strong>
      </div>
      <div class="col-md-4">
        <strong> <label class='control-label'> Picture </label> </strong>
      </div>
    </div>
    <hr/>
    <div class="row" style="text-align:center">
      <div class="col-md-4" >
       <%=  @product.name %>
      </div>
      <div class="col-md-4">
       <%= @product.price %>
      </div>
      <div class="col-md-4">
        <%= image_tag @product.images.first.photo_url(:thumb) , class:"img-circle" %>
      </div>
    </div>
    <hr/>
  </div>
</div>

</div>